#CONEXION A LA BASE DE DATOS
spring.application.name=api
# URL de conexion: protocolo + ip + puerto + nombre_bd
spring.datasource.url=${DB_HOST}/${DB_NAME}

# Credenciales
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver especifico de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto para que Hibernate optimice el SQL para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#configuracion para visualizar las queries exactas que JPA ejecuta contra la DB
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=never


#MODELO DE IA
server.port=8080

# URL del microservicio Python (ia-service)
inferencia.service.url=http://localhost:8000

# Tarifa de referencia (misma que model_metadata.json)
tarifa.referencia.usd_kwh=0.75